### ISSUE TITLE
请问d4rl_mujoco_dataset/halfcheetah_medium_replay-v2.hdf5在哪里获取

### ISSUE THREAD

**Issue by falsemail** [t6-thu/H2O#2]
-------------Env name: HalfCheetah-v2, variety: 2.0, unreal_dynamics: gravity-------------
Traceback (most recent call last):
  File "sim2real_sac_main.py", line 228, in <module>
    absl.app.run(main)
  File "/home/dell/anaconda3/envs/h2o/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/dell/anaconda3/envs/h2o/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "sim2real_sac_main.py", line 126, in main
    replay_buffer = MixedReplayBuffer(FLAGS.reward_scale, FLAGS.reward_bias, FLAGS.clip_action, num_state, num_action, task=env_name.split("-")[0].lower(), data_source=FLAGS.data_source, device=FLAGS.device, buffer_ratio=FLAGS.replaybuffer_ratio, residual_ratio=FLAGS.real_residual_ratio)
  File "/home/dell/codes/H2O/SimpleSAC/mixed_replay_buffer.py", line 23, in __init__
    with h5py.File(path, "r") as dataset:
  File "/home/dell/anaconda3/envs/h2o/lib/python3.7/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/dell/anaconda3/envs/h2o/lib/python3.7/site-packages/h5py/_hl/files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '../../d4rl_mujoco_dataset/halfcheetah_medium_replay-v2.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by t6-thu** [comment]
You can get the D4RL dataset by following the way https://github.com/Farama-Foundation/D4RL mentions.
